# IN CASE THE REPOSITORY IS DOWNLOADED, THIS NEEDS TO BE UPDATED BY THE USER, IT WILL BE ASKED TO BE UPDATED IN THE BEGINNING OF MAIN_PIPELINE.PY
general_path: '/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/'

# These paths are relative to the general path defined above, so they don't need to be updated by the user
paths_relative_to_general_path:
  customers_data_queries_csv: "Data_generator/Generated_data/customers_data_for_queries.csv"
  customers_data_models_csv: "Data_generator/Generated_data/customers_data_for_models.csv"
  macro_data_csv: "Data_generator/Generated_data/macro_data.csv" 
  customers_data_for_queries_db: "Data_generator/SQL_queries/Data/customers_data_for_queries.db"
  combined_data_pd_ldg_ead_irb_csv: "Output_data/customer_PD_LGD_EAD_STA_IRB/customer_data_PD_LGD_EAD_IRB.csv"
  data_generator_folder: "Data_generator/"
  pd_lgd_ead_folder: "PD_LGD_EAD_Modelling/"
  bank_statements_folder: "Bank_Statements/"
  generated_data_folder: "Data_generator/Generated_data/"
  interest_rates_folder: "Interest_rates/"
  pd_folder: "PD_LGD_EAD_Modelling/PD/"
  lgd_folder: "PD_LGD_EAD_Modelling/LGD/"
  ead_folder: "PD_LGD_EAD_Modelling/EAD/"
  gaussian_copula_folder: "PD_LGD_EAD_Modelling/Gaussian_copula_estimation/"
  joint_default_probabilities_folder: "Output_data/joint_def_prob/"

# Maximum number of periods (months) for the simulation ######################################################
max_simulation_periods: 60
##############################################################################################################

# THE REST OF THE PARAMETERS CAN OR CANNOT BE UPDATED, BUT THE GENERAL PATH NEEDS TO BE UPDATED OTHERWISE THE CODE WON'T RUN

####################################### Bank Statements parameters #########################################

initial_bank_values:
  reserve_ratio: 0.1 # How many of the assets need to be hold by the bank and not be lend at the beginning of the game
  reference_rate: 0.02 # The defined by the central bank rate at the beginning of the game
  saving_rate: 0.01 # The base rate paid by the bank to the account holders at the beginning of the game
  lending_rate_base: 0.04 # The base rate paid to the bank by the loan holders at the beginning of the game
  initial_deposits: 1000000 # Original deposits hold by the bsnk st the beginning of the game
  initial_equity: 100000 # Initial equity at the beginning of the game
  retained_earnings: 100000 # Initial retained earnings at the beginning of the game


####################################### Data generation parameters #########################################

### ------- Data_generator/data_generator.py

# General parameters ---->

number_years_previous_game: 5 # This is to generate the macroeconomic data for the previous years before the game

number_of_customers_1: 1000

# Parameters for variables generation ---->

# Name related
default_name_prefix: "name"

# Age related
age_min: 30
age_max: 65

# Education related
education: 
  levels:
    - "high school or lower"
    - "ausbildung"
    - "bachelor degree"
    - "post graduate degree"
  weights:
    - 0.3
    - 0.3
    - 0.3
    - 0.1

# Past credits related
past_credits:
  levels:
    - 0
    - 1
    - 2
    - 3
  weights:
    - 0.6
    - 0.3
    - 0.08
    - 0.02

# General probability that in one year the person will accumulate a not paid credit based on past credits
past_credits_sensibility: 0.1


# Dependents related
dependents:
  levels:
    - 0
    - 1
    - 2
    - 3
    - 4
  weights:
    - 0.6
    - 0.3
    - 0.06
    - 0.03
    - 0.01

# General probability that a person will have a new dependent 
dependents_sensitivity: 0.1 

### ------- Data_generator/data_generator_functions.py

# Parameters for variables generation ---->

# Profession related
professions:
  LowSkilled:
    levels:
      - "LowSkilled"
      - "Unemployed_LowSkilled"
    weights:
      - 0.9
      - 0.1
  MediumSkilled:
    levels:
      - "MediumSkilled"
      - "Unemployed_MediumSkilled"
    weights:
      - 0.9
      - 0.1
  HighSkilled:
    levels:
      - "HighSkilled"
      - "Unemployed_HighSkilled"
    weights:
      - 0.9
      - 0.1

# Social mobility parameters
social_mobility:
  LowSkilled:
    to_Unemployed_LowSkilled: 0.2
    to_LowSkilled: 0.7
    to_MediumSkilled: 0.1
    to_HighSkilled: 0.0
  Unemployed_LowSkilled:
    to_Unemployed_LowSkilled: 0.6
    to_LowSkilled: 0.35
    to_MediumSkilled: 0.05
    to_HighSkilled: 0.0
  MediumSkilled:
    to_Unemployed_MediumSkilled: 0.1
    to_LowSkilled: 0.1
    to_MediumSkilled: 0.7
    to_HighSkilled: 0.1
  Unemployed_MediumSkilled:
    to_Unemployed_MediumSkilled: 0.6
    to_MediumSkilled: 0.38
    to_HighSkilled: 0.02
    to_LowSkilled: 0.0
  HighSkilled:
    to_Unemployed_HighSkilled: 0.1
    to_LowSkilled: 0.0
    to_MediumSkilled: 0.1
    to_HighSkilled: 0.8
  Unemployed_HighSkilled:
    to_Unemployed_HighSkilled: 0.5
    to_MediumSkilled: 0.2
    to_HighSkilled: 0.3
    to_LowSkilled: 0.0

# Working sector related
working_sectors:
  LowSkilled:
    sectors:
      - "Construction"
      - "Agriculture"
      - "Manufacturing"
      - "Transportation"
      - "Cleaning Services"
    weights:
      - 0.2
      - 0.3
      - 0.2
      - 0.2
      - 0.1
  MediumSkilled:
    sectors:
      - "Nursing"
      - "Teacher"
      - "IT Support"
      - "Electrician"
      - "Artist"
    weights:
      - 0.2
      - 0.3
      - 0.2
      - 0.2
      - 0.1
  HighSkilled:
    sectors:
      - "Finance"
      - "Engineering"
      - "Research"
      - "Consultant"
      - "Doctor"
    weights:
      - 0.2
      - 0.3
      - 0.2
      - 0.2
      - 0.1

# Transition probabilities for working sectors are modeled randomly in data_dynamics.py

# Income related
# Assuming unemployement money is 50% of the income of the employed in the same skill category
income_params:
  LowSkilled:
    min: 1000
    max: 5000
  Unemployed_LowSkilled:
    min: 500
    max: 2500
  MediumSkilled:
    min: 1200
    max: 10000
  Unemployed_MediumSkilled:
    min: 600
    max: 5000
  HighSkilled:
    min: 1600
    max: 20000
  Unemployed_HighSkilled:
    min: 800
    max: 10000

# This is to define the type of function to generate income based on age
# We can have four types of functions: 
# linear: grows linearly with age, steady growth
# quadratic: grows quadratically with age, steady early growth then fast later growth
# exponential: grows exponentially with age, slow early growth then fast later growth
# logarithmic: grows logarithmically with age, fast early growth then stabilizes
# sigmoid: grows sigmoidally with age, slow early growth, fast middle growth, then stabilizes
# step: income jumps at certain age thresholds
type_of_function_income: "sigmoid"
step_steps: 5 # number of steps if step function is chosen


# Expenditure related
expenditure_params:
  low_income_params: # in case income lower than average income
    dependents: # left, mode, right for triangular distribution
      - [0.5, 0.7, 1.5] # for 0 dependents
      - [0.7, 0.8, 1.5] # for 1 dependent
      - [0.8, 0.9, 1.5] # for 2 dependents
      - [0.9, 1.0, 1.5] # for 3 dependents
      - [1.0, 1.1, 1.5] # for 4 dependents
  high_income_params: # in case income higher or equal than average income
    dependents: # left, mode, right for triangular distribution
      - [0.3, 0.5, 1.2] # for 0 dependents
      - [0.4, 0.6, 1.2] # for 1 dependent
      - [0.5, 0.7, 1.2] # for 2 dependents
      - [0.6, 0.8, 1.2] # for 3 dependents
      - [0.7, 0.9, 1.2] # for 4 dependents

# Credit characteristics related
credit_characteristics:
  duration_loan:
    duration_months:
      - 12
      - 24
      - 36
      - 48
      - 60
    weights:
      - 0.2
      - 0.3
      - 0.2
      - 0.2
      - 0.1
  percentage_monthly_income:
    max: 1.0
    min: 0.2
  types_of_loan:
    - "mortgages"
    - "auto loans"
    - "simple loans"

# Collateral related
collateral:
  types:
    - "house"
    - "car"
    - "liquid assets"
    - "none"
  thresholds:
    - 50000 # House
    - 20000 # Car
    - 0 # Liquid assets
    - 0 # None
  amount_per_type:
    HighSkilled:
      per_no_collateral: 0.10 # percentage of people with no collateral
      Boundaries: [10000, 80000] # min and max collateral value
    MediumSkilled:
      per_no_collateral: 0.20 # percentage of people with no collateral
      Boundaries: [10000, 50000] # min and max collateral value
    LowSkilled:
      per_no_collateral: 0.35 # percentage of people with no collateral
      Boundaries: [5000, 25000]  # min and max collateral value

# Estimated seizable assets related
seizable_assets_multiplier:
  HighSkilled: 1.2
  MediumSkilled: 1.0
  LowSkilled: 0.8

# y-variable related
y_variable:
  risk_settings:
    Unemployed_LowSkilled:
      base: 0.15 # base probability of default
      weights: [0.30, 0.6, 0.4] # base probability of default and weights (past credits, debt to income before credit, credit to income)
    LowSkilled:
      base: 0.08 # base probability of default
      weights: [0.20, 0.5, 0.3] # base probability of default and weights (past credits, debt to income before credit, credit to income)
    Unemployed_MediumSkilled:
      base: 0.12 # base probability of default
      weights: [0.30, 0.5, 0.3] # base probability of default and weights (past credits, debt to income before credit, credit to income)
    MediumSkilled:
      base: 0.05 # base probability of default
      weights: [0.20, 0.45, 0.25] # base probability of default and weights (past credits, debt to income before credit, credit to income)
    Unemployed_HighSkilled:
      base: 0.09 # base probability of default
      weights: [0.30, 0.45, 0.25] # base probability of default and weights (past credits, debt to income before credit, credit to income)
    HighSkilled:
      base: 0.02 # base probability of default
      weights: [0.20, 0.4, 0.2] # base probability of default and weights (past credits, debt to income before credit, credit to income)
  sector_risk_modifier: # extra risk modifier based on working sector
    LowSkilled:
      Construction: 0.03
      Agriculture: 0.02
      Manufacturing: 0.01
      Transportation: 0.025
      Cleaning Services: 0.04
    MediumSkilled:
      Nursing: -0.01
      Teacher: -0.015
      IT Support: 0.0
      Electrician: 0.01
      Artist: 0.03
    HighSkilled:
      Finance: -0.02
      Engineering: -0.015
      Research: -0.01
      Consultant: 0.0
      Doctor: -0.025

####################################### PD, LGD, EAD Modelling ###############################################

###### PD ##################################

### ------- PD_estimation.py

PD_main_function:
  neuronal_network:
    epochs: 20 # Number of epochs for training the neural network
    batch_size: 32 # Batch size for training the neural network
    first_layer_activation_function: 'tanh' # Activation function for the first layer of the neural network
    second_layer_activation_function: 'tanh' # Activation function for the second layer of the neural network
    third_layer_activation_function: 'sigmoid' # Activation function for the output layer of the neural network
  random_forests:
    n_estimators: 100 # Number of trees in the random forest model
    random_state: 42 # Random state for reproducibility
  others:
    iterations: 1 # number of iterations for Monte Carlo simulation, change it to 100 or more for better results

###### Interest rates ##################################

### ------- original_i_rates_estimation.py

interest_rates:
  base_rate: null # initial_bank_values:reference_rate defined above will be pulled using pythong in original_i_rates_estimation
  max_interest_rate: 0.5  # Maximum interest rate allowed. This one will be set by the bank, based on its risk appetite and other factors
  credit_to_income_ratio_factor: 0.04  # Factor for credit-to-income ratio
  loan_duration_factor: 0.01  # Factor for loan duration
  debt_factor: 0.02  # Factor for debt-to-income ratio
  asset_factor: 0.03  # Factor for estimated seizable assets

###### LGD ##################################

### ------- LGD_estimation.py

# Non-existign right now, as it relies right now heavily on the interest rates and the parameters above to generate them

###### EAD ##################################

### ------- EAD_estimation.py

# Non-existign right now

###### Gaussian_copula_estimation ##################################

### ------- Gaussian_factor_copula.py

gaussian_copula:
  third_step: # Simulate default indicators using a Gaussian factor copula model with group-level and macroeconomic factors.
    n_sim: 1000 # number of Monte Carlo simulations
    rho_macro: 0.1 # weight for macroeconomic factor
    rho_group: 0.2 # weight for group-level factors
  fifth_step: # Estimate the capital per borrower using the IRB approach.
    rho: 0.15 # Correlation parameter
  ninth_step: # In this part, the top N borrowers with the highest joint default probabilities for each borrower are identified
    top_n: 5 # number of top borrowers to identify




