"""In this module, we implement the Gaussian factor copula model to model the joint distribution of default probabilities 
and loss given default (LGD) for a portfolio of loans. The model uses a Gaussian copula to capture the dependence structure 
between the default probabilities and LGD, allowing for a flexible modeling of the joint distribution.

What is a Gaussian factor copula model?
A Gaussian factor copula model is a statistical model that captures the dependence structure between multiple random variables 
(in this case, default probabilities and LGD) using a Gaussian copula. The model assumes that the joint distribution of the 
random variables can be expressed as a combination of marginal distributions and a copula that describes the dependence structure.

Why do we need a Gaussian factor copula model?
The Gaussian factor copula model is useful for modeling the joint distribution of default probabilities and LGD in a portfolio of loans.
It allows us to capture the dependence structure between the default probabilities and LGD, which is important for risk management and portfolio optimization.
"""

# Package imports
import numpy as np
import sys
import os
import pandas as pd
from scipy.stats import norm, multivariate_normal
from scipy.optimize import minimize
from sklearn.preprocessing import StandardScaler

""" FIRST STEP: REVIEWED!
we will combine our data from the Data Generator module with our PDs generated in the PD_LGD_EAD_Modelling module.
This will allow us to have a complete dataset with all the necessary features for our Gaussian factor copula model
"""

# Read the csv file into a pandas DataFrame
data_path = '/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/Data_generator/Generated_data/customers_data_for_queries.csv'
data = pd.read_csv(data_path)

# Now we will import the PDs generated in the PD_LGD_EAD_Modelling module.

# Adjust path for module import
sys.path.append(os.path.abspath('/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/PD_LGD_EAD_Modelling/PD'))

# Import your data setup function
from PD_estimation import main as data_setup_main

PD_df, coef_dict, scores_df = data_setup_main()

# We combine data and PD_df, PD_df has no index, so we can concatenate them directly
combined_data = pd.concat([data, PD_df], axis=1)

""" SECOND STEP: REVIEWED!
Define the latent thresholds for the Gaussian factor copula model.
The latent thresholds are used to transform the marginal distributions into uniform marginals, which is a requirement for copula modeling.

We have three different models to estimate the default probabilities (PDs):
- Logistic Regression (LR)
- Neural Network (NN)
- Random Forest (RF)
# We will use the PDs generated by these models to define the latent thresholds.
"""

# Convert marginal PDs to normal quantile thresholds
for model in ['LR', 'NN', 'RF']:
    combined_data[f"default_threshold_{model}"] = norm.ppf(combined_data[f"PD_{model}"].clip(1e-5, 1 - 1e-5))


""" THIRD STEP: REVIEWED!
This step us aiming for a hierarchical Gaussian factor copula, where:
- Working sector and credit type define categorical risk groups, with latent group-level risk factors.
- A macroeconomic factor affects all borrowers, with borrower-specific sensitivity.
- Each borrower has idiosyncratic risk as well.

To implement this, we will:
 1. Treat working sector and credit type as discrete latent group-level factors — i.e., each category (e.g., sector=Retail) 
    has a group-specific latent factor that is shared among all borrowers in that group.
 2. Introduce a global macroeconomic factor that is shared by everyone.
 3. Each borrower has a personalized sensitivity to the macro factor.
 Default threshold:

𝑍𝑖 = sqrt(𝜌macro) ⋅ 𝐹macro + sqrt(𝜌group) ⋅ 𝐹group(i) + sqrt(1 − 𝜌macro − 𝜌group) ⋅ 𝜖𝑖

where:
- 𝑍𝑖 is the latent variable for borrower i
- 𝐹macro is the macroeconomic factor
- 𝐹group(i) is the group-level factor for borrower i
- 𝜖𝑖 is the idiosyncratic risk for borrower i
- 𝜌macro is the weight for the macroeconomic factor
- 𝜌group is the weight for the group-level factors

Assumptions:
- The macroeconomic factor is shared by all borrowers and has a weight of 𝜌macro.
- Each group (working sector and type of credit) has its own latent factor with weight 𝜌group.
- Each borrower has idiosyncratic risk represented by 𝜖𝑖.
- The total weight of the macro and group factors must be less than 1, i.e., 𝜌macro + 𝜌group < 1.
- The idiosyncratic risk 𝜖𝑖 is assumed to be normally distributed with mean 0 and variance 1.

In the end the default matrices represent the simulated default indicators for each borrower across multiple simulations.
Each row corresponds to a simulation, and each column corresponds to a borrower.
The values are 0 or 1, where 1 indicates a default in that simulation for that borrower.
Why are they useful?
The default matrices are useful for understanding the risk profile of the portfolio, estimating joint default probabilities,
and calculating capital requirements based on the simulated defaults. They allow us to analyze the impact of different factors on default probabilities and assess the overall risk exposure of the portfolio.
"""

def simulate_default_indicators_grouped(default_thresholds, data, n_sim=1000,
                                        rho_macro=0.1, rho_group=0.2):
    """
    Simulate default indicators using a Gaussian factor copula model with group-level and macroeconomic factors.

    Parameters:
    - default_thresholds: np.array of norm.ppf(PD)
    - data: DataFrame with 'working sector' and 'type of credit'
    - n_sim: number of Monte Carlo simulations
    - rho_macro: weight for macroeconomic factor
    - rho_group: weight for group-level factors

    Returns:
    - default_matrix: (n_sim, n_borrowers) array of 0/1 default outcomes
    """
    # Ensure the weights are valid
    assert (rho_macro + rho_group) < 1.0, "Total systemic weight must be less than 1"
    # Initialize the default matrix
    n_borrowers = len(data)
    default_matrix = np.zeros((n_sim, n_borrowers))

    # Define unique group combinations of working sector and type of credit (later on we can make it for each group and not as a combination)
    data['group_key'] = data['working sector'].astype(str) + "_" + data['type of credit'].astype(str)
    unique_groups = data['group_key'].unique()
    group_to_index = {g: i for i, g in enumerate(unique_groups)}
    borrower_groups = data['group_key'].map(group_to_index).values
    n_groups = len(unique_groups)

    # Precompute square roots for the weights of the equation
    sqrt_rho_macro = np.sqrt(rho_macro)
    sqrt_rho_group = np.sqrt(rho_group)
    sqrt_residual = np.sqrt(1 - rho_macro - rho_group)

    for sim in range(n_sim):
        # One macro factor per simulation
        F_macro = np.random.normal()

        # One latent factor per group
        F_group = np.random.normal(size=n_groups)

        # One idiosyncratic per borrower
        eps = np.random.normal(size=n_borrowers)

        # Map group-level factor to each borrower
        F_group_per_borrower = F_group[borrower_groups]

        # Combine all factors
        Z = sqrt_rho_macro * F_macro + sqrt_rho_group * F_group_per_borrower + sqrt_residual * eps

        # Apply thresholds
        default_matrix[sim] = (Z < default_thresholds).astype(int)

    return default_matrix

# Prepare default thresholds for each model
default_thresholds_dict = {
    model: combined_data[f"default_threshold_{model}"].values
    for model in ['LR', 'NN', 'RF']
}

# Simulate defaults for each model efficiently in a loop
default_matrix_dict = {}
for model, thresholds in default_thresholds_dict.items():
    default_matrix_dict[model] = simulate_default_indicators_grouped(thresholds, combined_data)

# Unpack results for later use
default_matrix_LR = default_matrix_dict['LR']
default_matrix_NN = default_matrix_dict['NN']
default_matrix_RF = default_matrix_dict['RF']


# # Lets visualize the default matrices for each model but in a sensitive way so that we can understand what is happening
# # We will not plot them, because it is very diffuse, but we will print some statistics about the default matrices
# def print_default_matrix_stats(default_matrix, model_name):
#     """
#     Print statistics about the default matrix for a given model.
    
#     Parameters:
#     - default_matrix: np.array of shape (n_simulations, n_borrowers)
#     - model_name: name of the model (e.g., 'LR', 'NN', 'RF')
#     """
#     print(f"Statistics for {model_name} Default Matrix:")
#     print(f"Shape: {default_matrix.shape}")
#     print(f"Total Defaults (sum across simulations): {np.sum(default_matrix)}")
#     print(f"Mean Defaults per Borrower: {np.mean(np.sum(default_matrix, axis=0))}")
#     print(f"Default Rate (mean across simulations): {np.mean(default_matrix)}")
#     print("-" * 40)
# # Print statistics for each model's default matrix
# print_default_matrix_stats(default_matrix_LR, 'Logistic Regression (LR)')
# print_default_matrix_stats(default_matrix_NN, 'Neural Network (NN)')
# print_default_matrix_stats(default_matrix_RF, 'Random Forest (RF)')


"""NOTES: THE FOLLOWING WILL FOLLOW A CUSTOMER-LEVEL APPROACH, WHERE WE WILL SIMULATE LOSSES FOR EACH BORROWER
WE COULD ALSO DO A SIMULATION-LEVEL APPROACH, WHERE WE WOULD SIMULATE LOSSES FOR EACH SIMULATION,
BUT THIS WILL MAY BE CARRIED OUT IN A FUTURE STEP."""


"""FOURTH STEP: REVIEWED!
HERE IS WHERE WE NEED TO ADD OUR LGD simulation values and the EAD values (which will be the exposure values).
Simulate Portfolio Losses
In this step, we will simulate the portfolio losses based on the default indicators generated in the previous step.
For now we will assume LGD=1 and EAD=1, so the loss will be equal to the default indicator.

What is the loss?
The loss in this context refers to the financial loss incurred by the bank when a borrower defaults on their loan.
It is typically calculated as the product of the exposure at default (EAD) and the loss given default (LGD).

As we already have our calculated LGD, we will bring them here to calculate the losses.
The EAD will be the total amount of the loan/credit, so we will calculate it as follows:
EAD = df['credit: monthly amount'] * df['requested_loan_duration']

The final loss for each borrower will be calculated as:
Loss = default_indicator(from the default matrix) * LGD * EAD
Where:
- default_indicator is the value from the default matrix (0 or 1)
- LGD is the loss given default that we calcualted in another file for each borrower
- EAD is the exposure at default that we calculated above
"""

# LET'S IMPORT THE LGD VALUES ################################
# Adjust path for module import
sys.path.append(os.path.abspath('/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/PD_LGD_EAD_Modelling/LGD'))

# Import your data setup function
from LGD_estimation import main as data_setup_main

lgd_estimates = data_setup_main()

# Concatenate the LGD estimates with the combined_data DataFrame and give the column a name
# The LGDs were not estimated using any techniques and we only have one column with the LGD values
# Remember that the LGDs were saved as a pd.Series
combined_data['LGD'] = lgd_estimates
##############################################################


# LET"S CALCULATE THE EAD VALUES ################################
# Calculate EAD as the total amount of the loan/credit
combined_data['EAD'] = combined_data['credit: monthly amount'] * combined_data['requested_loan_duration']
#################################################################

# Broadcast LGD and EAD to the shape of (n_simulations, n_borrowers)
LGD = combined_data['LGD'].values
EAD = combined_data['EAD'].values

# Initialize a dictionary to hold the expected losses (EL) for each model
# This will be performed on a customer level, averaging the losses across simulations instead of at a simulation level
for model, matrix in zip(['LR', 'NN', 'RF'], [default_matrix_LR, default_matrix_NN, default_matrix_RF]):
    combined_data[f'EL_{model}'] = np.mean(matrix, axis=0) * combined_data['LGD'] * combined_data['EAD']

"""FIFTH STEP: CHECK CALCULATION AGAIN!
Estimate the capital per borrower using the IRB approach.
The IRB (Internal Ratings-Based) approach is a method used by banks to calculate regulatory capital requirements for credit risk.
The IRB formula is given by:
    Ki = LGDi * normal_cdf((normal_ppf(PDi) + sqrt(rho) * normal_ppf(0.999))/sqrt(1 - rho)) - PDi * LGDi
where:
- Ki is the capital requirement for borrower i
- LGDi is the loss given default for borrower i
- PDi is the probability of default for borrower i
- rho is the correlation parameter (assumed to be 0.15 for this example)   
- normal_cdf is the cumulative distribution function of the standard normal distribution    
- normal_ppf is the percent-point function (inverse of CDF) of the standard normal distribution
- 0.999 is the confidence level for the unexpected loss calculation which is typically used in the IRB approach

PLEASE NOTEE: the IRB capital requirement may be and it is expected to be bigger than the expected loss (EL) calculated above.
This is because the IRB approach accounts for unexpected losses and the correlation between borrowers, while the
expected loss is simply the average loss based on the default indicators.
Also the IRB capital requirement accounts for 99% of the worst-case scenario.
Our calculation formula includes a VaR (Value at Risk) which is the 99.9% quantile of the standard normal distribution.
That is a very extreme tail, so the IRB capital requirement will be higher than the expected loss.
"""

def irb_capital_per_borrower(EAD, PD, LGD, rho):
    q = norm.ppf(0.999)
    pd_term = norm.ppf(PD)
    capital = LGD * norm.cdf((pd_term + np.sqrt(rho) * q) / np.sqrt(1 - rho)) - PD * LGD
    required_capital = capital * EAD  # This one is to get the actual capital requirement per borrower
    return required_capital

rho = 0.15  # Correlation parameter

# You can adjust LGD here if you want per borrower, for now keep it simple with LGD=1 or use actual LGD values.
# Using actual LGD per borrower might be more realistic:
LGD_values = combined_data['LGD'].values

for model in ['LR', 'NN', 'RF']:
    combined_data[f"IRB_Capital_{model}"] = irb_capital_per_borrower(
        EAD=combined_data['EAD'].values,
        PD=combined_data[f"PD_{model}"].values,
        LGD=combined_data['LGD'].values,
        rho=rho
    )
    
"""SIXTH STEP: REVIEWED!
Let's clean up the combined_data DataFrame by removing unnecessary columns.
"""
    
# We will also eliminate the default thresholds columns as they are not needed anymore
combined_data.drop(columns=["default_threshold_LR", "default_threshold_NN", "default_threshold_RF"], inplace=True)

""" SEVENTH STEP: REVIEWED!
Save the final combined data with joint default probabilities to a new CSV file.
"""
# Save the combined data to a new CSV file
combined_data_path = '/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/Data_generator/Generated_data/PD_LGD_EAD_IRB/customer_data_plus_PDs&IRB_Cap_req.csv'
combined_data.to_csv(combined_data_path, index=False)
    

"""EIGHTH STEP: REVIEWED!
Estimate Joint Default Probabilities
In this step, we will estimate the joint default probabilities using the Gaussian factor copula model.

Some questions to consider:

    1. What are joint default probabilities?
    Joint default probabilities refer to the likelihood of multiple borrowers defaulting simultaneously. They are crucial for understanding the risk exposure of a portfolio, as they capture the correlation between defaults across different borrowers. Estimating these probabilities helps in assessing the overall risk and making informed decisions regarding capital allocation and risk management.

    2. Why do we need to estimate joint default probabilities?
    Joint default probabilities are essential for understanding the likelihood of multiple borrowers defaulting simultaneously, which is crucial for risk management and capital allocation in a portfolio of loans. By estimating these probabilities, we can better assess the overall risk exposure and make informed decisions regarding capital requirements and risk mitigation strategies.

    3. How do joint default probabilities relate to the Gaussian factor copula model?
    The Gaussian factor copula model captures the dependence structure between the default probabilities of different borrowers. By simulating defaults based on common factors and sensitivity parameters, we can estimate the joint default probabilities as the mean of the simulated default matrix across multiple simulations. This allows us to account for the correlation between borrowers' defaults and provides a more accurate representation of the portfolio's risk profile.

    4. How to interpret the joint default probabilities?
    Joint default probabilities are interpreted as the likelihood of multiple borrowers defaulting simultaneously. A higher joint default probability indicates a greater risk of simultaneous defaults, while a lower probability suggests a more stable portfolio. These probabilities can be used to assess the overall risk exposure of the portfolio and inform capital allocation decisions.

    5. Are joint default probabilities different from marginal default probabilities?
    Yes, joint default probabilities differ from marginal default probabilities. Marginal default probabilities refer to the likelihood of an individual borrower defaulting, while joint default probabilities consider the simultaneous defaults of multiple borrowers. The Gaussian factor copula model allows us to estimate these joint probabilities by capturing the dependence structure between borrowers' defaults, which is not reflected in marginal probabilities alone.

    6. Do differen borrowers have different joint default probabilities?
    Yes, different borrowers can have different joint default probabilities based on their individual characteristics, such as credit scores, industry sectors, and other risk factors. The Gaussian factor copula model captures these differences by incorporating borrower-specific information and the common factors that influence defaults across the portfolio. As a result, the joint default probabilities will vary for each borrower depending on their unique risk profile and the overall portfolio dynamics.

    7. Do different borrorwers share the same joint default probabilities?
    Yes, different borrowers can share the same joint default probabilities if they are influenced by the same common factors and sensitivity parameters in the Gaussian factor copula model. However, the joint default probabilities can also vary among borrowers based on their individual characteristics and the specific common factors that affect them. The model captures both shared and unique influences on defaults, allowing for a nuanced understanding of joint default probabilities across the portfolio.
"""

def estimate_pairwise_joint_defaults(default_matrix):
    """
    Estimate pairwise joint default probabilities from a simulated default matrix.

    Parameters:
    - default_matrix: np.array of shape (n_simulations, n_borrowers)

    Returns:
    - joint_probs: np.array of shape (n_borrowers, n_borrowers)
                   where joint_probs[i, j] is P(default_i AND default_j)
                   
    This function is very informative as it calculates the probability of joint defaults for each pair of borrowers
    based on the simulated default matrix. It provides insights into the correlation between defaults across different borrowers
    and helps in understanding the overall risk exposure of the portfolio.
    """
    n_sim, n_borrowers = default_matrix.shape
    joint_probs = (default_matrix.T @ default_matrix) / n_sim
    return joint_probs

# Estimate joint default probabilities for each model
joint_default_probabilities_LR = estimate_pairwise_joint_defaults(default_matrix_LR)
joint_default_probabilities_NN = estimate_pairwise_joint_defaults(default_matrix_NN)
joint_default_probabilities_RF = estimate_pairwise_joint_defaults(default_matrix_RF)

"""NINTH STEP: Function to identify the top joint default borrowers
This function identifies the top N borrowers with the highest joint default probabilities for each borrower.
It returns a DataFrame with borrower IDs and their top N joint default borrowers.
This is useful for understanding the risk concentration in the portfolio and identifying borrowers that are likely to default together.
This information can be used for risk management, capital allocation, and portfolio optimization."""
# Identify for each borrower the top 5 borrowers with the highest joint default probabilities and save to a CSV file
def top_joint_default_borrowers(joint_probs, borrower_ids, top_n=5):
    """
    Identify the top N borrowers with the highest joint default probabilities for each borrower,
    and return both the borrower IDs and the corresponding probabilities.

    Parameters:
    - joint_probs: np.array of shape (n_borrowers, n_borrowers)
    - borrower_ids: list of borrower IDs or indices
    - top_n: number of top borrowers to identify

    Returns:
    - top_borrowers_df: DataFrame with borrower IDs, their top N joint default borrowers, and probabilities
    """
    # Just to check the shape of joint_probs and borrower_ids
    #assert joint_probs.shape[0] == joint_probs.shape[1], "joint_probs must be square"
    #assert joint_probs.shape[0] == len(borrower_ids), "Mismatch with borrower_ids"

    # n_borrowers is the number or rows or of columns in joint_probs
    n_borrowers = joint_probs.shape[0]
    results = {} # Initialize a dictionary to hold results
    
    # Iterate over each borrower to find their top N joint default borrowers
    for i in range(n_borrowers):
        row = joint_probs[i].copy()
        row[i] = -1  # Exclude self
        top_indices = np.argsort(row)[-top_n:][::-1]
        top_ids = [borrower_ids[idx] for idx in top_indices]
        top_probs = [joint_probs[i, idx] for idx in top_indices]
        results[borrower_ids[i]] = [val for pair in zip(top_ids, top_probs) for val in pair]

    # Define the number of columns based on top_n
    # Each borrower will have top_n pairs of (ID, Probability)
    columns = []
    for j in range(top_n):
        columns.extend([f"Top_{j+1}_ID", f"Top_{j+1}_Prob"])

    # Create a DataFrame from the results dictionary
    top_borrowers_df = pd.DataFrame.from_dict(results, orient='index', columns=columns)
    return top_borrowers_df

# Assuming combined_data has an index of borrower IDs
borrower_ids = combined_data.index.tolist() 
# Get top joint default borrowers for each model
top_joint_borrowers_LR = top_joint_default_borrowers(joint_default_probabilities_LR, borrower_ids)
top_joint_borrowers_NN = top_joint_default_borrowers(joint_default_probabilities_NN, borrower_ids)
top_joint_borrowers_RF = top_joint_default_borrowers(joint_default_probabilities_RF, borrower_ids)

# Define the path to save the joint default probabilities
joint_default_probs_path = "/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/Data_generator/Generated_data/joint_def_prob/"

# Save the top joint default borrowers to CSV files for each model
top_joint_borrowers_LR.to_csv(joint_default_probs_path + 'top_joint_borrowers_LR.csv', index_label='Borrower_ID')
top_joint_borrowers_NN.to_csv(joint_default_probs_path + 'top_joint_borrowers_NN.csv', index_label='Borrower_ID')
top_joint_borrowers_RF.to_csv(joint_default_probs_path + 'top_joint_borrowers_RF.csv', index_label='Borrower_ID')