"""Here we will define the functions needes to generate the X and y data for the model.

We have different classifications for the variables:
1. It has its own function (O) or it is generated in the main function (M)
2. Independent (I), which means generated without other variables and dependent (D) variables which are generated using other X variables as their parameters.
3. Fixed (F), which means that they remain the same for the enite simulation and readjusted (R) variables which do not. 
Plus a variable is called recalculated (K) if they do not depend on any random process themselves, but they are recaulcuated given that its parameters (other variables) were recalculated, but do not follow any direct randomness calculation in the function like a markov chain or a state-matrix.
Plus we have another type called hybrid (H) which follows a different rule
4. Cummulative (C) variables, which means that they are generated based on the previous period values and the current period values and not cummulative (N)

The data will be generated in the following way:
1. Generate the X variables:
    - Generate the name of the person --> (M, I, F, N) Totally independent variable generated in the main function and remais fixed the entire simulation
    - Generate the age of the person --> (M, I, R, C) Totally independent variable generated in the main function and will change in the simulation (every 12 periods)
    - Generate the education level of the person --> (M, I, F, N) Totally independent variable generated in the main function and will be assumed to remain fixed the entire simulation
    _ Generate the number of unpaid past credits --> (M, I, F, N) Totally independent variable generated in the main function and remais fixed the entire simulation
    - Generate the number of dependents --> (M, I, R, C) Totally independent variable generated in the main function and will change in the simulation (readjusted given a matrix of possible states will be generated per period, like a Markov chain)
    - Generate the profession of the person --> (O, D, F, N) Generated based on the education level of the person and will be assumed to remain fixed the entire simulation
    - Genertae the working sector of the person --> (O, D, F, N) Generated based on the profession of the person and will be assumed to remain fixed the entire simulation
    - Generate the monthly income of the person --> (O, D, R, N) Generated based on the profession, age of the person, number of dependents and income_predefined_parameters (should be adjusted every period, we need a Markov chain to make it more realistic, so we can add a possible extra parameter that will be a matrix of states)
    - Generate the monthly expenditure of the person --> (O, D, R, N) Generated based on income, number of dependents and income_predefined_parameters (should be adjusted every period, we need a Markov chain to make it more realistic, so we can add a possible extra parameter that will be a matrix of states)
    - Generate the savings-debt of a person --> (M, D, K, C) Generated based on the difference between income and expenditure, which is a cummulative variable (it will be recalculated every period, but it will not be generated by any random process)
    - Generate the debt to income ratio of a person before the credit --> (M, D, K, N) Generated as the ratio between the debt calculated before as percentage of the monhtly income (it will be recalculated every period, but it will not be generated by any random process)
    _ Generate the credit amount (monthly value) --> (O, D, H, N) Generated based on the income and the percentage of the monthly income (it will be recalculated every period just for the people who have not taken the credit yet, for the others it does not matter, once the credit contract is signed, the amount will remain fixed, but it will not be generated by any random process)
    - Generate the credit to income ratio --> (O, D, K, N) Generated as the ratio between the credit amount (monthly value) and the income (it will be recalculated every period, but it will not be generated by any random process)
    - Generate the requested loan duration --> (O, D, K, N) Generated as the duration of the loan in months (it will be recalculated every period, but it will not be generated by any random process)
    - Generate the debt to income ratio of a person before the credit --> (M, D, K, N) Generated as the ratio between the debt calculated before as percentage of the monhtly income (it will be recalculated every period, but it will not be generated by any random process)
    - Generate the collateral value --> (O, D, R, N) Generated based on the profession (however, to add some randomness, we can can recalculate the collateral maybe also by using some Markov Chains of possible states, to add more variability to the simulation)
    - Generate the seizable assets --> (O, D, R, N) Generated based on the monthly income, savings, profession and collateral value (it will be recalculated every period, but it will not be generated by any random process)
2. Generate the y variables:
    - Generate the default or not default variable (which is a binary variable) --> (O, D, R, N) Generated based on the profession, past credits, debt to income ratio before credit and credit to income ratio (it will be recalculated every period, but it will not be generated by any random process)
    """
    
    

"""Packages for data generation."""
import pandas as pd
import numpy as np
import random



"""Generate the profession based on the education level.
Note: This variable will remain fixed for the entire simulation."""

def generate_profession(education):
    if education == "high school or lower":
        return random.choices(["LowSkilled", "Unemployed_LowSkilled"], weights=[0.9, 0.15], k=1)[0]
    if education == "ausbildung":
        return random.choices(["MediumSkilled", "Unemployed_MediumSkilled"], weights=[0.9, 0.1], k=1)[0]
    if education in ["bachelor degree", "post graduate degree"]:
        return random.choices(["HighSkilled", "Unemployed_HighSkilled"], weights=[0.9, 0.05], k=1)[0]
  
    
"""Generate the working sector based on the profession.
Note: This variable will remain fixed for the entire simulation for simplicity.
We will have three different sectors: LowSkilled, MediumSkilled and HighSkilled.
And we will have five different professions in each sector.
Each sector has an intrisic risk, that is this is a factor that will be used to calculate the default label.
Factors will be the working sector, the age and thee number of dependents.
Note 2: We can add some randomness to the working sector, so we can add some Markov chains to make it more realistic."""

def generate_working_sector(profession):
    if "LowSkilled" in profession:
        return random.choices(["Construction", "Agriculture", "Manufacturing", "Transportation", "Cleaning Services"], weights=[0.2, 0.3, 0.2, 0.2, 0.1], k=1)[0]
    elif "MediumSkilled" in profession:
        return random.choices(["Nursing", "Teacher", "IT Support", "Electrician", "Artist"], weights=[0.2, 0.3, 0.2, 0.2, 0.1], k=1)[0]
    elif "HighSkilled" in profession:
        return random.choices(["Finance", "Engineering", "Research", "Consultant", "Doctor"], weights=[0.2, 0.3, 0.1, 0.2, 0.2], k=1)[0]
    else:
        return None

    
"""Generate the monthly income and expenditure based on the profession and age.
Note: These variables will be readjusted every period, so we need to use a Markov chain to make it more realistic."""   
  
# Define income parameters for different profession levels and age ranges
income_parameters = {
    ("LowSkilled", "Unemployed_LowSkilled"): {
        (30, 35): {"mean": 1000, "std_dev": 200, "max_income": 2000},
        (36, 40): {"mean": 1200, "std_dev": 200, "max_income": 2400},
        (41, 45): {"mean": 1500, "std_dev": 250, "max_income": 3000},
        (46, 50): {"mean": 1800, "std_dev": 300, "max_income": 3600},
        (51, 55): {"mean": 2000, "std_dev": 350, "max_income": 4000},
        (56, 60): {"mean": 2200, "std_dev": 400, "max_income": 4300},
        (61, 65): {"mean": 2400, "std_dev": 600, "max_income": 4500},
    },
    ("MediumSkilled", "Unemployed_MediumSkilled"): {
        (30, 35): {"mean": 1800, "std_dev": 300, "max_income": 4000},
        (36, 40): {"mean": 2300, "std_dev": 400, "max_income": 5000},
        (41, 45): {"mean": 2600, "std_dev": 500, "max_income": 6000},
        (46, 50): {"mean": 3000, "std_dev": 600, "max_income": 7000},
        (51, 55): {"mean": 3500, "std_dev": 800, "max_income": 8000},
        (56, 60): {"mean": 4000, "std_dev": 800, "max_income": 9000},
        (61, 65): {"mean": 5000, "std_dev": 1000, "max_income": 10000},
    },
    ("HighSkilled", "Unemployed_HighSkilled"): {
        (30, 35): {"mean": 3000, "std_dev": 500, "max_income": 10000},
        (36, 40): {"mean": 4500, "std_dev": 700, "max_income": 15000},
        (41, 45): {"mean": 6000, "std_dev": 1000, "max_income": 20000},
        (46, 50): {"mean": 7000, "std_dev": 1500, "max_income": 25000},
        (51, 55): {"mean": 8000, "std_dev": 2000, "max_income": 30000},
        (56, 60): {"mean": 9000, "std_dev": 3000, "max_income": 40000},
        (61, 65): {"mean": 10000, "std_dev": 4000, "max_income": 50000},
    }
}

# To calculate the monthly income and expenditure
def generate_income_expense(profession_undertake, current_age, num_dependents):
    # Iterate over income parameters for each profession group
    for profession_group, age_ranges in income_parameters.items():
        # Check if profession_undertake is one of the professions in the profession_group tuple
        if profession_undertake in profession_group:
            # Iterate over the age ranges and income parameters
            for age_range, params in age_ranges.items():
                if age_range[0] <= current_age <= age_range[1]:
                    mean_income = params["mean"]
                    std_dev = params["std_dev"]
                    max_income = params["max_income"]
                    unemployement_money = mean_income * 0.5  # 50% of mean income for unemployment

                    # If profession_undertake contains the word "Unemployed" before "_", return the unemployment money
                    if profession_undertake.split("_")[0] == "Unemployed":
                        income = unemployement_money
                        expenditure = generate_expenditure(income, mean_income, num_dependents) # The belong to the population under mean_income
                        return income, expenditure
                    
                    # If profession_undertake does not contain the word "Unemployed", generate income with an specific rule
                    else:
                        calc_income = int(np.random.normal(mean_income, std_dev))
                        income = max(unemployement_money, min(calc_income, max_income))  
                        expenditure = generate_expenditure(income, mean_income, num_dependents)
                        return income, expenditure

# Support function to calculate the expenditure
def generate_expenditure(income, mean_income, num_dependents):
    # Values for low and for high income people (lower possible value, mode, higher possible value) depending on the number of dependents
    low_income_params = [(0.5, 0.7, 1.5), (0.7, 0.8, 1.5), (0.8, 0.9, 1.5), (0.9, 0.9, 1.5), (0.9, 1.0, 1.5)]
    high_income_params = [(0.5, 0.6, 1.5), (0.6, 0.65, 1.5), (0.7, 0.75, 1.5), (0.7, 0.75, 1.5), (0.8, 0.85, 1.5)]
    # The parameters that should be taken depend on whether the income is below or above the mean income
    params = low_income_params if income < mean_income else high_income_params
    # Here we recover the parameters
    left, mode, right = params[min(num_dependents, 4)]  # Ensure index stays within range
    # The expenditure is calculated given a rule of min, mode, max
    expenditure = income * np.random.triangular(left=left, mode=mode, right=right)
    return expenditure


"""Generate the amount of the credit requested, the credit to income ratio and the requested loan duration.
Note: This variable will be generated based on the income and the percentage of the monthly income.
The percentage of the monthly income will be a random value between 25% and 150% of the monthly income."""  

def generate_credit_requested(income): ### It will depend on the income
    # First define the duration of the loan
    credit_term_months = random.choices([12, 24, 36, 48, 60], weights=[0.2, 0.3, 0.2, 0.2, 0.1], k=1)[0]
    # Now define the percentage of the monthly income
    # The will maximum enter as for a credit that represent between 20% and 100% the maximum credit requested is equal to 1 time the monthly income
    percentage_of_monthly_income = random.uniform(0.2, 1.0)
    # Duration of the loan income given the current income
    loan_expected_income = income * credit_term_months
    # The credit requested is equal to the income during the duration of the credit times the percentage of the monthly income
    credit_requested = loan_expected_income * percentage_of_monthly_income
    # Calculate the credit monthly value
    credit_requested_monthly = credit_requested / credit_term_months
    # Calculate the percentage of the credit requested over the monthly income
    percentage_credit_month_income = credit_requested_monthly/income
    # Return the values
    return credit_term_months, credit_requested, credit_requested_monthly, percentage_credit_month_income


"""Generate the collateral value.
Note: This variable will be generated based on the profession of the person.
Note 2: We maybe want that the collateral can increase or decrease over time, so we can add some randomness to the collateral value."""

def calculate_collateral(profession):
    if "HighSkilled" in profession: # If the person is HighSkilled, even if currently unemployed
        # random.random() returns a float number between 0 and 1
        if random.random() < 0.10: # 10 % of the people do not have collateral
            return 0
        else: # 90 % have a collateral between 10,000 and 80,000
            return random.randint(10000, 80000)
    elif "MediumSkilled" in profession: # If the person is HighSkilled, even if currently unemployed
        if random.random() < 0.20: # 20 % of the people do not have collateral
            return 0
        else: # 80 % have a collateral between 10,000 and 50,000
            return random.randint(10000, 50000)
    else: # If Lowskilled
        if random.random() < 0.35: # 35 % of the people do not have collateral
            return 0
        else: # 65 % have a collateral between 5,000 and 25,000
            return random.randint(5000, 25000)


"""Generate the seizable assets.
Note: This variable will be generated based on the monthly income, savings, profession and collateral value.
Note 2: As we will set monhtly income and collateral to be changing with Markov Chains and states, this variable will be recalculated every period."""

def estimate_seizable_assets(monthly_income, savings, profession, collateral):
    # Base asset estimation as a portion of income and savings
    # This is a proxy, people with higher income, tend to have higher assets
    # If the savinds are negative, and higher than 2 times the monthy income this will draw this to be negative
    # In the end, if no assets can be seizured, it means that maybe it is not convenient for the bank to actually give the loan
    base_asset = savings + 2 * monthly_income

    # People that are High-Skilled tend to have more assets to be seized, even if they are currently unemployed
    if "HighSkilled" in profession:
        base_asset *= 1.2
    elif "MediumSkilled" in profession:
        base_asset *= 1.0
    else:
        base_asset *= 0.8

    # If they have a collateral, more sizes are
    base_asset += collateral

    # Add some noise to simulate unpredictability
    # That means given some processes in normal life, it is not always sure that 100% of the collateral can be recovered without cost
    base_asset *= np.random.normal(1, 0.1)  # 10% variation

    # To ensure that if nothing can be seized, because in the end a negative value is returned, then we get a zero
    return max(base_asset, 0)


""" Generate the default label (0/1) based on financial risk factors.
Note: This variable will be generated based on the profession, past credits, debt to income ratio before credit and credit to income ratio.
Note 2: This is our y-variable and in the end we added some randomness to account for the error in the model."""

def generate_default_label(profession, sector, past_credits, debt_to_income_ratio_before_credit, credit_to_income_ratio):
    
    # This simulates a default label (0/1) based on financial risk factors.
    # What we will use will be the:
    
    # Configurable risk settings per profession
    risk_settings = {
        "Unemployed_LowSkilled":     {"base": 0.15, "weights": (0.30, 0.6, 0.4)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
        "LowSkilled":                {"base": 0.08, "weights": (0.20, 0.5, 0.3)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
        "Unemployed_MediumSkilled": {"base": 0.12, "weights": (0.30, 0.5, 0.3)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
        "MediumSkilled":            {"base": 0.05, "weights": (0.20, 0.45, 0.25)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
        "Unemployed_HighSkilled":   {"base": 0.09, "weights": (0.30, 0.45, 0.25)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
        "HighSkilled":              {"base": 0.02,  "weights": (0.20, 0.4, 0.2)}, # base probability of default and weights (past credits, debt to income before credit, credit to income)
    }
    
    # Sector-level risk modifiers
    sector_risk_modifier = {
        # LowSkilled sectors tend to have a positive risk premium
        "Construction": 0.03,
        "Agriculture": 0.02,
        "Manufacturing": 0.01,
        "Transportation": 0.025,
        "Cleaning Services": 0.04,
        # MediumSkilled sectors tend to have a neutral risk premium
        "Nursing": -0.01,
        "Teacher": -0.015,
        "IT Support": 0.0,
        "Electrician": 0.01,
        "Artist": 0.03,
        # HighSkilled sectors tend to have a negative risk premium
        "Finance": -0.02,
        "Engineering": -0.015,
        "Research": -0.01,
        "Consultant": 0.0,
        "Doctor": -0.025,
    }

    # setting variable is set to retrieve the element of risk_settings for the profession given
    settings = risk_settings.get(profession)
    # In case there is the profession given for the function does not match any of the professions above listed
    if not settings:
        raise ValueError(f"Unknown profession: {profession}")
    
    # Get sector risk modifier
    sector_modifier = sector_risk_modifier.get(sector, 0)  # Default to 0 if unknown sector
    
    # Defining the weigths for the calcualtion of the probability of default
    w1, w2, w3 = settings["weights"]
    # Defining the base probability of default
    base = settings["base"]

    # Calculating the risk factor with the weigths
    risk_factor = past_credits * w1 + debt_to_income_ratio_before_credit * w2 + credit_to_income_ratio * w3
    
    # Add small random noise to simulate real-world unpredictability in default behavior
    # This makes the dataset more realistic and prevents deterministic labels for identical inputs
    noise = random.uniform(-0.1, 0.1)
    
    # Final default probability includes profession risk, sector modifier, and added noise
    default_probability = min(1, max(0, base + risk_factor + sector_modifier + noise))

    # We want a non-deterministic y-categorical variable that will make that same profiles will not always lead to the same result
    # So even if two people may fall on the same profile, maybe they will not have the same default label
    # return 1 if random.random() < default_probability else 0
    return int(random.random() < default_probability)
# that means that if 1 is returned, the person will default, if 0 is returned, the person will not default