"""In this module, we implement the Gaussian factor copula model to model the joint distribution of default probabilities and loss given default (LGD) for a portfolio of loans. The model uses a Gaussian copula to capture the dependence structure between the default probabilities and LGD, allowing for a flexible modeling of the joint distribution."""

# Package imports
import numpy as np
import sys
import os
import pandas as pd
from scipy.stats import norm, multivariate_normal
from scipy.optimize import minimize
from sklearn.preprocessing import StandardScaler

""" FIRST STEP:
we will combine our data from the Data Generator module with our PDs generated in the PD_LGD_EAD_Modelling module.
This will allow us to have a complete dataset with all the necessary features for our Gaussian factor copula model
"""

# Read the csv file into a pandas DataFrame
data_path = '/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/Data_generator/Generated_data/customers_data_for_queries.csv'
data = pd.read_csv(data_path)

# Now we will import the PDs generated in the PD_LGD_EAD_Modelling module.

# Adjust path for module import
sys.path.append(os.path.abspath('/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/PD_LGD_EAD_Modelling/PD'))

# Import your data setup function
from PD_estimation import main as data_setup_main

PD_df, coef_dict, scores_df = data_setup_main()

# We combine data and PD_df, PD_df has no index, so we can concatenate them directly
combined_data = pd.concat([data, PD_df], axis=1)

# Save the combined data to a new CSV file
combined_data_path = '/Users/bonjour/Documents/AI/Projects/GitHub/BankGame/Data_generator/Generated_data/customer_data_plus_PDs.csv'
combined_data.to_csv(combined_data_path, index=False)

""" SECOND STEP:
Define the latent thresholds for the Gaussian factor copula model.
The latent thresholds are used to transform the marginal distributions into uniform marginals, which is a requirement for copula modeling.

We have three different models to estimate the default probabilities (PDs):
- Logistic Regression (LR)
- Neural Network (NN)
- Random Forest (RF)
# We will use the PDs generated by these models to define the latent thresholds.
"""

# With the logistic regression model
combined_data["default_threshold_LR"] = norm.ppf(combined_data["PD_LR"])

# With the Neural Network model
combined_data["default_threshold_NN"] = norm.ppf(combined_data["PD_NN"])

# With the Random Forest model
combined_data["default_threshold_RF"] = norm.ppf(combined_data["PD_RF"])


""" THIRD STEP:
Define the Fatcor Copula Structure. 
Fi is the common factor for the ith variable, and it is assumed to be normally distributed.
p: is the sensitivity of the ith variable to the common factor Fi.
We will have three common factors: working sector, credit type and macroeconomic factor.
The working sector factor and the credit type factor are columns in the combined data DataFrame.
The macroeconomic factor is a random variable that we will generate from a normal distribution.
Therefore working sector and credit type will have impacts on the PDs of each specific group, 
while the macroeconomic factor will have a global impact on all PDs.

The relationship betweenten the common factors and the latent thresholds is given by the following equation:
# default_threshold_i = sqr(p) * F_i + sqr(1 -p) * e_i
# where e_i is a random variable that is normally distributed with mean 0 and standard deviation 1.
"""

# With our combined data, we will define the common factors and the sensitivity parameters.
# Define the common factors
def generate_common_factors(data, n_samples=1000):
    """
    Generate common factors for the Gaussian factor copula model.
    
    Parameters:
    - data: DataFrame containing the combined data with PDs.
    - n_samples: Number of samples to generate for the common factors.
    
    Returns:
    - common_factors: DataFrame with common factors.
    """
    # Generate a random macroeconomic factor
    macroeconomic_factor = np.random.normal(0, 1, n_samples)
    
    # Extract working sector and credit type as categorical variables
    working_sector = pd.get_dummies(data['working_sector'], drop_first=True).values
    credit_type = pd.get_dummies(data['credit_type'], drop_first=True).values
    
    # Combine all factors into a single DataFrame
    common_factors = np.hstack((working_sector, credit_type, macroeconomic_factor.reshape(-1, 1)))
    
    return common_factors
common_factors = generate_common_factors(combined_data, n_samples=len(combined_data))

# Define our macroeconomic factor
def generate_macroeconomic_factor(n_samples=1000):
    """
    Generate a random macroeconomic factor.
    
    Parameters:
    - n_samples: Number of samples to generate for the macroeconomic factor.
    
    Returns:
    - macroeconomic_factor: Array of macroeconomic factors.
    """
    # Generate a random macroeconomic factor from a normal distribution
    macroeconomic_factor = np.random.normal(0, 1, n_samples)
    
    return macroeconomic_factor
macroeconomic_factor = generate_macroeconomic_factor(n_samples=len(combined_data))

# Define the sensitivity parameter to the common and macroeconomic factors
def generate_sensitivity_parameters(n_factors, n_samples=1000):
    """
    Generate sensitivity parameters for the common factors.
    
    Parameters:
    - n_factors: Number of common factors.
    - n_samples: Number of samples to generate for the sensitivity parameters.
    
    Returns:
    - sensitivity_params: Array of sensitivity parameters.
    """
    # Generate random sensitivity parameters from a uniform distribution
    sensitivity_params = np.random.uniform(0, 1, (n_samples, n_factors))
    
    return sensitivity_params
sensitivity_params = generate_sensitivity_parameters(n_factors=common_factors.shape[1], n_samples=len(combined_data))

""" FOURTH STEP:
Simulate defaults using the Gaussian factor copula model.
The simulation will be based on the common factors, sensitivity parameters, and the latent thresholds defined earlier.
In the end we will have a default matrix that indicates whether each borrower defaults or not based on the simulated common factors and sensitivity parameters. 
How to interpret the default matrix?
The default matrix will have a shape of (n_simulations, n_borrowers), where each row corresponds to a simulation and each column corresponds to a borrower.
"""

def simulate_default_indicators(default_thresholds, common_factors, sensitivity_params, n_sim=1000):
    """
    Simulate default indicators using Gaussian factor copula.
    
    Parameters:
    - default_thresholds: np.array of norm.ppf(PD)
    - common_factors: np.array (n_borrowers, n_factors)
    - sensitivity_params: np.array (n_borrowers, n_factors)
    - n_sim: number of Monte Carlo simulations

    Returns:
    - default_matrix: (n_sim, n_borrowers) array of 0/1 default outcomes
    What is a default_matrix?
    - Each row corresponds to a simulation, and each column corresponds to a borrower.
    - A value of 1 indicates a default, and 0 indicates no default.
    """
    n_borrowers, n_factors = common_factors.shape
    default_matrix = np.zeros((n_sim, n_borrowers))

    for sim in range(n_sim):
        # Simulate one common macro shock per sim (shared across borrowers)
        F = np.random.normal(0, 1, size=n_factors)  # systemic factors
        eps = np.random.normal(0, 1, size=n_borrowers)  # idiosyncratic
        
        Z = np.sum(np.sqrt(sensitivity_params) * F, axis=1) + \
            np.sqrt(1 - np.sum(sensitivity_params, axis=1)) * eps
        
        default_matrix[sim] = (Z < default_thresholds).astype(int)
        
    return default_matrix

# Let"s get the default matrix for each model
default_thresholds_LR = combined_data["default_threshold_LR"].values
default_thresholds_NN = combined_data["default_threshold_NN"].values 
default_thresholds_RF = combined_data["default_threshold_RF"].values
# Simulate defaults for each model
default_matrix_LR = simulate_default_indicators(default_thresholds_LR, common_factors, sensitivity_params)
default_matrix_NN = simulate_default_indicators(default_thresholds_NN, common_factors, sensitivity_params)
default_matrix_RF = simulate_default_indicators(default_thresholds_RF, common_factors, sensitivity_params)   



